### ISSUE TITLE
پیشنهاد برای سایت

### ISSUE THREAD

**Issue by realleonine** [alaatv/alaatv#18]
باسلام و عرض خسته نباشید
لطفا برای آموزش های صفرتاصد قابلیت دانلود کامل فیلم ها رو به صورت یکجا برای هر درس بزارین خیلی سخته و وقت گیره یکی یکی دانلود کردنشون
همچنین برای هر درس یا برای هرمجموعه آموزش میتونید فرومی رو بذارید برای رفع اشکال توسط درسی توسط اساتید
باتشکر

**Comment by sohrabafard** [comment]
انجمن آلاء هست برای رفع اشکال
