### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by imantlp105** [alaatv/alaatv#2]
لطفا در بروزرسانی جدید سایت برای هر مجموعه فیلم لینکی را قرار دهید تا بشور تمام فیلم های ان مجموعه را با کیفیتی معین دانلود کرد بصورت رار 

برای مثال لینکی باشد تا فیلم های دینی را بشود یکجا دانلو کرد

**Comment by imantlp105** [comment]
لطفا در به روزرسانی جدید سایت برای هر مجموعه فیلم لینکی را بگذارید تا بشور تمام فیلم های آن مجموعه با کیفیتی معین دانلود کند.

برای مثال، لینکی تا به فیلم های دینی می تواند به صورت یکجا بارگیری شود

**Comment by sohrabafard** [comment]
این کار خوب نیست، به جای این در سایت جدید دسترسی به دیگر جلسات یک فیلم راحت تر می شود.
این درخواست رو با اجازه می بندیم.
