### ISSUE TITLE
سایت جدید

### ISSUE THREAD

**Issue by 8080frnz** [alaatv/alaatv#28]
قبول دارین اپدیت سایت خیلی خوب شده؟
من ک خیلی راضیم واقعا دسته تمام مسئولین الاء درد نکنه ؛تا اینجا ک خیلی سایت خوب بوده :-)

**Comment by sohrabafard** [comment]
خدا رو شکر منتظر پیشنهادات شما برای امکانات بهتر و بیشتر هستیم.
لطفا هر امکانی را در یک 
Issue
جدا ثبت کنید.
