### ISSUE TITLE
سبد خرید

### ISSUE THREAD

**Issue by uadminu** [alaatv/alaatv#38]
سلام من جزوه هایی که قبلا خریده بودم از سبد خرید پاک شده و خالی شده!!!
@sohrabafard

**Comment by uadminu** [comment]
و دیگه جزوه های رایگان رو هم نمیشه دانلود کرد
مثل: https://alaatv.com/c/8388

**Comment by sohrabafard** [comment]
سلام فیلم ها و جزوات پولی در قسمت فیلم و جزوه پروفایلتون قرار داره
alaatv.com/asset

اون لینک رو هم بررسی می کنیم فردا صبح

کس دیگه ای هم هست که همچین مشکلی داشته باشه؟

**Comment by sohrabafard** [comment]
https://github.com/alaatv/alaatv/issues/40
